//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCsv.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NCsv.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Could not convert {0} to a boolean value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BooleanConvertError {
            get {
                return ResourceManager.GetString("BooleanConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not convert {0} to a date and time value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DateTimeConvertError {
            get {
                return ResourceManager.GetString("DateTimeConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The format of {0} is incorrect. Please set it in {1} format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DateTimeFormatError {
            get {
                return ResourceManager.GetString("DateTimeFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The format of {0} is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidFormatError {
            get {
                return ResourceManager.GetString("InvalidFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The item does not exist in the CSV. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemNotExistError {
            get {
                return ResourceManager.GetString("ItemNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set {0} to be within {1} digits. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaxLengthError {
            get {
                return ResourceManager.GetString("MaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set {0} to a value that is less than or equal to {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumberMaxValueError {
            get {
                return ResourceManager.GetString("NumberMaxValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set {0} to a value that is greater than or equal to {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumberMinValueError {
            get {
                return ResourceManager.GetString("NumberMinValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set {0} to a value between {1} and {2}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumberOutOfRangeError {
            get {
                return ResourceManager.GetString("NumberOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set {0} to a numeric value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumericConvertError {
            get {
                return ResourceManager.GetString("NumericConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set {0} to a value with an integer part of no more than {1} digits and a decimal part of no more than {2} digits. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrecisionAndScaleError {
            get {
                return ResourceManager.GetString("PrecisionAndScaleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set {0} to a value with no more than {1} digits. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrecisionError {
            get {
                return ResourceManager.GetString("PrecisionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
    }
}
